package/Editor/AndroidPostBuildProcessor.cs, package/Editor/IOSPostBuildProcessor.cs, package/Runtime/Plugins/Android/UnityHelper.java, package/Runtime/Scripts/Internal/Android.cs
- Updated Nimbus Android SDK to 1.10.3
- Downgraded Kotlin reflect dependency to 1.3.61 to prevent dependency upgrades
- Fixed issue where builds fail on Windows machines due to missing iOS dependencies
=> Updated Nimbus Android SDK to 1.10.3

package/Editor/AndroidPostBuildProcessor.cs, package/Runtime/Plugins/Android/UnityHelper.java, package/Runtime/Scripts/Internal/Android.cs, package/Runtime/Scripts/Internal/Editor.cs, package/Runtime/Scripts/Internal/IOS.cs, package/Runtime/Scripts/Internal/NimbusAPI.cs, package/Runtime/Scripts/Internal/NimbusAdUnit.cs, sample-app/ProjectSettings/ProjectSettings.asset, sample-app/ProjectSettings/UnityConnectSettings.asset
- Updated Nimbus SDK to 1.11.4
- Added helper methods to split request and render piece of the SDK
=> Android Plugin Updates

com.adsbynimbus.nimbus/Editor/AndroidBuildDependencies.cs, com.adsbynimbus.nimbus/Editor/IOSBuildDependencies.cs
Fixes a missing commit from #42
=> Updated Nimbus SDKs to 2.10.0

com.adsbynimbus.nimbus/Editor/AndroidBuildDependencies.cs, com.adsbynimbus.nimbus/Editor/IOSBuildDependencies.cs, com.adsbynimbus.nimbus/Runtime/Plugins/iOS/NimbusBinding.mm, com.adsbynimbus.nimbus/Runtime/Plugins/iOS/NimbusHelper.swift, com.adsbynimbus.nimbus/Runtime/Plugins/iOS/NimbusManager.swift, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/Android.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/Editor.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/IOS.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/Network/NimbusClient.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/NimbusAPI.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/NimbusAdUnit.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/RequestBuilder/BannerExtension.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/RequestBuilder/BidRequestExtension.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/RequestBuilder/VideoExtension.cs, com.adsbynimbus.nimbus/Runtime/Scripts/NimbusManager.cs, com.adsbynimbus.nimbus/package.json
Android: 2.18.0 - [Changelog](https://docs.adsbynimbus.com/docs/sdk/android/changelog#id-2.18.0)
iOS: 2.20.0 - [Changelog](https://docs.adsbynimbus.com/docs/sdk/ios/changelog#id-2.20.0)
- Added exception handling for request errors
- Added IFV and ATTS to request on IOS
- Added OMID flag to banner and video api array
=> Package: 1.3.0 Release

com.adsbynimbus.nimbus/Editor/IOSPostBuildProcessor.cs, com.adsbynimbus.nimbus/Editor/NimbusManagerCreator.cs, com.adsbynimbus.nimbus/Runtime/Plugins/RTB.Tests/Properties/AssemblyInfo.cs, com.adsbynimbus.nimbus/Runtime/Plugins/RTB.Tests/Tests.cs, com.adsbynimbus.nimbus/Runtime/Plugins/RTB/Request/Eid.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/Network/NimbusClient.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/NimbusAdUnit.cs, com.adsbynimbus.nimbus/Runtime/Scripts/NimbusManager.cs
https://adsbynimbus.monday.com/boards/5360942780/pulses/7449654211
https://adsbynimbus.monday.com/boards/5360942780/pulses/7449731563
=> EID RTB Update & Additional Logging

com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/Network/NimbusClient.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.ScriptableObjects/NimbusSDKConfiguration.cs
Included GZIP compression and decompression for requests/responses.
=> Implemented GZIP for Networking

com.adsbynimbus.nimbus/Editor/AndroidBuildDependencies.cs, com.adsbynimbus.nimbus/Editor/AndroidPostBuildProcessor.cs, com.adsbynimbus.nimbus/Editor/IOSPostBuildProcessor.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.ScriptableObjects/NimbusSDKConfiguration.cs, com.adsbynimbus.nimbus/VersionConstants.cs, com.adsbynimbus.nimbus/package.json
=> Supporting Non-EDM4U Builds

com.adsbynimbus.nimbus/Editor/AndroidPostBuildProcessor.cs, com.adsbynimbus.nimbus/Editor/NimbusSDKDependencies.xml, com.adsbynimbus.nimbus/VersionConstants.cs
Updated iOS and Android SDK Versions as well as changing a check for EDM4U.
=> Updated SDK Versions and EDM4U Check

com.adsbynimbus.nimbus/Runtime/Plugins/Android/UnityHelper.java, com.adsbynimbus.nimbus/VersionConstants.cs
Removing 2 unneeded Android imports and updating version constants
=> Changes needed for 1.9.0 Release

com.adsbynimbus.nimbus/Editor/AndroidBuildDependencies.cs, com.adsbynimbus.nimbus/Editor/AndroidPostBuildProcessor.cs, com.adsbynimbus.nimbus/Editor/IOSPostBuildProcessor.cs, com.adsbynimbus.nimbus/Editor/NimbusManagerCreator.cs, com.adsbynimbus.nimbus/Editor/ThirdPartyMacros.cs, com.adsbynimbus.nimbus/Runtime/Plugins/Android/UnityHelper.java, com.adsbynimbus.nimbus/Runtime/Plugins/RTB/Request/User.cs, com.adsbynimbus.nimbus/Runtime/Plugins/iOS/NimbusBinding.mm, com.adsbynimbus.nimbus/Runtime/Plugins/iOS/NimbusManager.swift, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/Android.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/IOS.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/Interceptor/ThirdPartyDemand/UnityAds/UnityAdsAndroid.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/Interceptor/ThirdPartyDemand/UnityAds/UnityAdsIOS.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/Utility/StaticMethod.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.ScriptableObjects/NimbusSDKConfiguration.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.ScriptableObjects/NimbusSDKConfigurationPropertiesEditor.cs
Unity Ads Integration for Rewarded ads.
=> Unity ads Integration

com.adsbynimbus.nimbus/Editor/AndroidPostBuildProcessor.cs
Updating for better gradle build logic.
=> Updating Android Gradle Script

com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/Android.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/IOS.cs, com.adsbynimbus.nimbus/VersionConstants.cs
Small Bug Fixes for iOS and Android when multiple third parties are enabled.
Constants Update for 1.10.0
=> Small Bug Fixes and Constants Update

com.adsbynimbus.nimbus/Editor/AndroidBuildDependencies.cs, com.adsbynimbus.nimbus/Editor/AndroidPostBuildProcessor.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/Network/NimbusClient.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/NimbusAdUnit.cs, com.adsbynimbus.nimbus/Runtime/Scripts/NimbusManager.cs
Android Collections version added for build.gradle, JAVA 8 Support added for play services ads library, No-fill errors / network error handling updated.
=> Fixes for Android Collections Errors, JAVA 8 Support, and No-Fill Network Errors

com.adsbynimbus.nimbus/VersionConstants.cs
=> Updated Version to 1.10.1

com.adsbynimbus.nimbus/Editor/NimbusSDKDependencies.xml, com.adsbynimbus.nimbus/Runtime/Plugins/Android/UnityHelper.java, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/Interceptor/ThirdPartyDemand/AdMob/AdMobAndroid.cs, com.adsbynimbus.nimbus/VersionConstants.cs
New Android helpers were added in 2.28.2 that have been implemented in the Unity SDK.
=> Updating AdMob to use New Android Helpers

com.adsbynimbus.nimbus/Runtime/Plugins/Android/UnityHelper.java, com.adsbynimbus.nimbus/Runtime/Plugins/RTB/Request/Regs.cs, com.adsbynimbus.nimbus/Runtime/Plugins/iOS/NimbusBinding.mm, com.adsbynimbus.nimbus/Runtime/Plugins/iOS/NimbusManager.swift, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/Interceptor/ThirdPartyDemand/MobileFuse/MobileFuseIOS.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/NimbusPrivacyHelpers.cs, com.adsbynimbus.nimbus/Runtime/Scripts/NimbusManager.cs
Privacy updates to fetch privacy fields from iOS and Android and add them to the bid request.
=> Privacy Updates

com.adsbynimbus.nimbus/package.json
Updated package.json version number.  Also added a backlog item to create a github action to check for matching version numbers in package.json and VersionConstants.cs.
=> Updated Package.json Version Number

com.adsbynimbus.nimbus/Editor/NimbusManagerCreator.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.ScriptableObjects/NimbusSDKConfigurationPropertiesEditor.cs
Updated UI to show if MobileFuse is enabled or not and fixed a small UI bug with Unity Ads.
=> Small UI Updates

com.adsbynimbus.nimbus/Runtime/Plugins/iOS/NimbusManager.swift, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/LiveRamp/NimbusLiveRampHelpers.cs
Issues with LiveRamp when not enabled.
=> Small issues around LiveRamp

com.adsbynimbus.nimbus/VersionConstants.cs, com.adsbynimbus.nimbus/package.json
Updated version numbers for new release.
=> Version Number Updates

com.adsbynimbus.nimbus/Editor/NimbusSDKDependencies.xml, com.adsbynimbus.nimbus/Runtime/Plugins/Android/UnityHelper.java, com.adsbynimbus.nimbus/Runtime/Plugins/RTB/Request/BidRequest.cs, com.adsbynimbus.nimbus/Runtime/Plugins/RTB/Response/BidResponse.cs, com.adsbynimbus.nimbus/Runtime/Plugins/iOS/NimbusBinding.mm, com.adsbynimbus.nimbus/Runtime/Plugins/iOS/NimbusManager.swift, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/Session/NimbusSessionHelpers.cs, com.adsbynimbus.nimbus/Runtime/Scripts/NimbusManager.cs, com.adsbynimbus.nimbus/VersionConstants.cs
Added Session Depth and tracking to the bid request.
=> Session Depth and Tracking

com.adsbynimbus.nimbus/Editor/NimbusSDKDependencies.xml, com.adsbynimbus.nimbus/Runtime/Plugins/iOS/NimbusManager.swift, com.adsbynimbus.nimbus/VersionConstants.cs, com.adsbynimbus.nimbus/package.json
Updated to include the most recent iOS & Android versions as well as updated the version number for a new release.
=> Android & iOS Version Updates

com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/Interceptor/SkAdNetworkIOS.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/Interceptor/ThirdPartyDemand/APS/ApsAndroid.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/Interceptor/ThirdPartyDemand/TaskExtensions.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/Interceptor/ThirdPartyDemand/Vungle/VungleAndroid.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Tests/InterceptorTest.cs, com.adsbynimbus.nimbus/Runtime/Scripts/NimbusManager.cs
Android did not cooperate well with the 2s timeout implementation.
=> Async Bug Fixes

com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/RequestBuilder/BidRequestExtension.cs, com.adsbynimbus.nimbus/Runtime/Scripts/Nimbus.Internal/RequestBuilder/NimbusRtbBidRequestHelper.cs
=> Trimming Position Field
